TOKEN: 123123:token
LOG_LEVEL: INFO
ADMIN_LISTS:
  - 238637902
THANKS_STIKERS: 
  - CAACAgIAAxkBAAOiZRDnD4XJdYuBXTzf_Ot9KH25iyEAApASAAIaWglJ8pDuOlI6QjUwBA
  - CAACAgUAAxkBAAPWZRDy6v1yVvzJooV2GNk-pY-wavQAAwcAAtoWIVcEnn_e8QQJzTAE
  - CAACAgIAAxkBAAPYZRDzfXzT2uEuRFaT60-qWx0WxwQAAt0UAAL3k-BLzzHccROJDFIwBA
  - CAACAgIAAxkBAAPoZRD1CHcrtFXxnDPz_7xWdVJ3gIAAAmsPAAK-szFLPqniW1UzO6cwBA
  - CAACAgIAAxkBAAPqZRD1JvNuYpszjfLwCqTOt_ld9_oAAhUjAAKRKlBKjqFPrejpn7kwBA

HELLO_MESSAGE: f"Hello, {user.full_name}"
HELLO_STIKERS: 
 - CAACAgIAAxkBAAIBNWURDvuxhT0vyCU3lQ8mgcXq9HvOAAJGDAACaxlYSnsuqbefOaqFMAQ
 - CAACAgUAAxkBAAIBN2URDwusbf2WYg4VUYGP9ndtF2I8AALsCAAC8bOxVsrcu--rZPA1MAQ
 - CAACAgIAAxkBAAIBOWURDyUNxMLr3njRheRt6mYO3fxxAAKlFwACH-fZS06o7pjr9LwHMAQ
 - CAACAgQAAxkBAAIBO2URDyyf4jfHEpUu1C4p_X64A-UpAAKGCgACnA8hUFPsN6KDkvltMAQ
 - CAACAgIAAxkBAAIBPWURD1ZHh-Dn8CbP3ZLR19iBkAEvAAKHLQAC6OcRS-qxKdoUxdgdMAQ

GOODBYE_MESSAGE: f"Fumo fren no more, goodbye {message.left_chat_member.full_name}"
GOODBYE_STIKERS: 
 - CAACAgIAAxkBAAIBP2URD2su4idILHCpEVniQJ2ItvF4AAIrDwACxx24SqWKrif9QzgWMAQ
 - CAACAgIAAxkBAAIBQWURD5F2lvBOtQZ-kb_hYJUkeBi0AAK6JgACa9BYShGQ3ksaTfYvMAQ